$axure.loadCurrentPage({
  "url":"登录页.html",
  "generationDate":new Date(1427789312736.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"088ca5a54c3745dea065756081fa21ad",
    "type":"Axure:Page",
    "name":"登录页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f74579dc420b4e8ba2a6e60429c73c11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":29},
            "size":{
              "width":1347,
              "height":501},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423244223ce64931be39b8d370102897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":1347,
                  "height":501},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"acb9ac7f358d402998325d1b814b7569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":260},
            "size":{
              "width":330,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3849a5b736014541bc63e9b82d2917b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":260},
                "size":{
                  "width":330,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"1935572925e24ac3b4fbaa99498c7574",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "size":{
              "width":1347,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72e2abc514e74f0dbf7e88efd96471ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "size":{
                  "width":1347,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"4a42dab2b1ae4e1baf0c8e11750e225c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":30,
              "y":4},
            "size":{
              "width":210,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40d0d75b0ec04fa7b82cd6c8b37208ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":4},
                "size":{
                  "width":210,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36047b563d0345d18245253cbc8182e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1286,
              "y":4},
            "size":{
              "width":27,
              "height":19},
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ab30ed44ba84d05afece2da9082b860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1286,
                  "y":4},
                "size":{
                  "width":27,
                  "height":19},
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"625a88a2479c4aad9aaaea806de9609a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":150,
              "y":40},
            "size":{
              "width":289,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0294c08ab1d34220aa5391bf65923662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":40},
                "size":{
                  "width":289,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"446af2ebb0064bfaa7ac2ed55029428b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":156},
            "size":{
              "width":559,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6334f2043db46ddaca8bc6aa9ed4dd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":156},
                "size":{
                  "width":559,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u12.jpg"}},
{
          "id":"f3bac6fbbef04d3b8aaedc6d0bfda446",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF33545D},
            "location":{
              "x":790,
              "y":156},
            "size":{
              "width":390,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fc713c7b2c476b81c86c796cc9a449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33545D},
                "location":{
                  "x":790,
                  "y":156},
                "size":{
                  "width":390,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u14.png"}},
{
          "id":"7126a51e0f6046deb1d9b212d06144e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":529},
            "size":{
              "width":1347,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e93c1035a949420c8201edc1efb9f270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":529},
                "size":{
                  "width":1347,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u16.png"}},
{
          "id":"f4635d6f33314aab9780e6f010551206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":820,
              "y":170},
            "size":{
              "width":41,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0080c32da99645eb8a790ffb9dd7b4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":820,
                  "y":170},
                "size":{
                  "width":41,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"288a06a5fc5f4268ac8a495c7458abb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":860,
              "y":237},
            "size":{
              "width":260,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e940a1fdd3491ea7b62fe1e7edf792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":860,
                  "y":237},
                "size":{
                  "width":260,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u20.png"}},
{
          "id":"da26f056a20d4987ae9481f6d9acb08c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":860,
              "y":300},
            "size":{
              "width":260,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb463847b7344a9b7f41cdc46f64a38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":860,
                  "y":300},
                "size":{
                  "width":260,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u20.png"}},
{
          "id":"fb45fba088744aecb2e9190e0288dcd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":201},
            "size":{
              "width":390,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u24_line.png"}},
{
          "id":"19ac73e4e4f74391988ae6a4ead6c703",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":860,
              "y":366},
            "size":{
              "width":260,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b386c33aaa574ebba90bfbadf4d5b9e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":860,
                  "y":366},
                "size":{
                  "width":260,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u25.png"}},
{
          "id":"ba4da05d8cd74cc9914681c72695ee3a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":1347,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u27_line.png"}},
{
          "id":"c8d3ef19cfe84978b16383ee950e04e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF585E64},
            "location":{
              "x":570,
              "y":531},
            "size":{
              "width":140,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5e559fdf83426783356ef6134b641a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF585E64},
                "location":{
                  "x":570,
                  "y":531},
                "size":{
                  "width":140,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u28.png"}},
{
          "id":"256034a923374eada61e0458462ca3ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":80,
              "y":541},
            "size":{
              "width":435,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b2adf805bae443581b223b1a0992b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":541},
                "size":{
                  "width":435,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f74579dc420b4e8ba2a6e60429c73c11":{
      "scriptId":"u0"},
    "423244223ce64931be39b8d370102897":{
      "scriptId":"u1"},
    "acb9ac7f358d402998325d1b814b7569":{
      "scriptId":"u2"},
    "3849a5b736014541bc63e9b82d2917b5":{
      "scriptId":"u3"},
    "1935572925e24ac3b4fbaa99498c7574":{
      "scriptId":"u4"},
    "72e2abc514e74f0dbf7e88efd96471ad":{
      "scriptId":"u5"},
    "4a42dab2b1ae4e1baf0c8e11750e225c":{
      "scriptId":"u6"},
    "40d0d75b0ec04fa7b82cd6c8b37208ad":{
      "scriptId":"u7"},
    "36047b563d0345d18245253cbc8182e6":{
      "scriptId":"u8"},
    "6ab30ed44ba84d05afece2da9082b860":{
      "scriptId":"u9"},
    "625a88a2479c4aad9aaaea806de9609a":{
      "scriptId":"u10"},
    "0294c08ab1d34220aa5391bf65923662":{
      "scriptId":"u11"},
    "446af2ebb0064bfaa7ac2ed55029428b":{
      "scriptId":"u12"},
    "e6334f2043db46ddaca8bc6aa9ed4dd4":{
      "scriptId":"u13"},
    "f3bac6fbbef04d3b8aaedc6d0bfda446":{
      "scriptId":"u14"},
    "94fc713c7b2c476b81c86c796cc9a449":{
      "scriptId":"u15"},
    "7126a51e0f6046deb1d9b212d06144e3":{
      "scriptId":"u16"},
    "e93c1035a949420c8201edc1efb9f270":{
      "scriptId":"u17"},
    "f4635d6f33314aab9780e6f010551206":{
      "scriptId":"u18"},
    "0080c32da99645eb8a790ffb9dd7b4f3":{
      "scriptId":"u19"},
    "288a06a5fc5f4268ac8a495c7458abb9":{
      "scriptId":"u20"},
    "d9e940a1fdd3491ea7b62fe1e7edf792":{
      "scriptId":"u21"},
    "da26f056a20d4987ae9481f6d9acb08c":{
      "scriptId":"u22"},
    "abb463847b7344a9b7f41cdc46f64a38":{
      "scriptId":"u23"},
    "fb45fba088744aecb2e9190e0288dcd8":{
      "scriptId":"u24"},
    "19ac73e4e4f74391988ae6a4ead6c703":{
      "scriptId":"u25"},
    "b386c33aaa574ebba90bfbadf4d5b9e1":{
      "scriptId":"u26"},
    "ba4da05d8cd74cc9914681c72695ee3a":{
      "scriptId":"u27"},
    "c8d3ef19cfe84978b16383ee950e04e0":{
      "scriptId":"u28"},
    "9d5e559fdf83426783356ef6134b641a":{
      "scriptId":"u29"},
    "256034a923374eada61e0458462ca3ad":{
      "scriptId":"u30"},
    "2b2adf805bae443581b223b1a0992b3d":{
      "scriptId":"u31"}}});